### ISSUE TITLE
Contexual Analysis - Proc, Func

### ISSUE THREAD

**Issue by 2359451d** [2359451d/L4-Source-Repo#6]
# Remark

* See book page 15, **we are allowed to reuse those reserved words as identifiers (contrast to special-symbols/word-symbol e.g. `array`,`begin`)**, BUT this would [introduce confusion which is not recommended](#)
* Recursive Call Allowed

# Tasks

- [x] Proc - simple decl & stat
![image](https://user-images.githubusercontent.com/46606028/144785632-e7ef415e-455f-49fc-aeac-e02869e2c984.png)
![image](https://user-images.githubusercontent.com/46606028/144786260-a1563b6c-670c-4112-bd1d-33be5476131e.png)

* Allowed empty statements,

- [x] Func - Simple Decl & Stat

* at least 1 assignment statement which assigns a value of the result type to func id

- [x] Proc - Nested Decl 
- [x] Func - Nested Decl

**Comment by 2359451d** [comment]
**Restrict redeclaring any function, procedure identifiers, (this will cause ambiguity)**

```pascal
{$mode iso}
program nestedProcTest;
var
  result :Integer;
function sum:Integer;
  var
    left: Integer;
    right: Integer;
    sum: Char;
  function add(left, right: Integer):Integer;
    begin
      add:= left+right;
    end;
  begin
    sum:= 'c'; {local var?}
    WriteLn(sum);
//    left:=1;
//    right:=2;
//    sum:=add(left,right);
//    WriteLn(sum);
  end;

begin
  result:=sum;
  WriteLn(result);
end.
```

![image](https://user-images.githubusercontent.com/46606028/149438356-f410cec8-3f93-4e90-94f2-5300e1e65c78.png)
